import { PortfolioLogo, PortfolioProject } from './portfolio.models';

const innovationIcons = [
  'fa-robot',
  'fa-flask',
  'fa-code',
  'fa-diagram-project',
  'fa-people-group',
  'fa-book-open',
  'fa-database',
  'fa-plug',
  'fa-chart-line',
  'fa-gears',
  'fa-headset',
  'fa-chart-pie',
  'fa-mobile-screen',
  'fa-cloud-arrow-up',
  'fa-lightbulb',
  'fa-wand-magic-sparkles',
];
const logo = (
  file: string,
  label: string,
  source: PortfolioLogo['source'] = 'brand',
): PortfolioLogo => ({
  src: `assets/img/technology-logos/${file}.svg`,
  label,
  source,
});
const innovationLogos: PortfolioLogo[][] = [
  [
    logo('concept-bot', 'AI Platform', 'concept'),
    logo('anthropic', 'Anthropic'),
    logo('langchain', 'LangGraph'),
    logo('crewai', 'CrewAI'),
  ],
  [
    logo('python', 'Python'),
    logo('fastapi', 'FastAPI'),
    logo('langchain', 'LangGraph'),
    logo('crewai', 'CrewAI'),
  ],
  [logo('fastapi', 'FastAPI')],
  [logo('langchain', 'LangGraph')],
  [logo('crewai', 'CrewAI')],
  [
    logo('concept-search', 'Retrieval', 'concept'),
    logo('postgresql', 'pgvector'),
    logo('concept-database', 'Vector Store', 'concept'),
  ],
  [
    logo('postgresql', 'pgvector'),
    logo('qdrant', 'Qdrant'),
    logo('concept-database', 'Vector Database', 'concept'),
  ],
  [
    logo('concept-bot', 'OpenAI', 'concept'),
    logo('anthropic', 'Anthropic'),
    logo('googlegemini', 'Gemini'),
    logo('concept-cloud-cog', 'Azure OpenAI', 'concept'),
  ],
  [
    logo('opentelemetry', 'OpenTelemetry'),
    logo('grafana', 'Grafana'),
    logo('concept-workflow', 'AI Evaluation', 'concept'),
  ],
  [
    logo('githubcopilot', 'GitHub Copilot'),
    logo('concept-bot', 'OpenAI Agents', 'concept'),
    logo('langchain', 'LangGraph'),
    logo('crewai', 'CrewAI'),
  ],
  [
    logo('concept-messages-square', 'Support Assistant', 'concept'),
    logo('concept-bot', 'OpenAI', 'concept'),
    logo('concept-search', 'RAG', 'concept'),
  ],
  [
    logo('apachesuperset', 'Apache Superset'),
    logo('grafana', 'Grafana'),
    logo('concept-chart-no-axes-combined', 'Analytics', 'concept'),
  ],
  [
    logo('angular', 'Angular'),
    logo('ionic', 'Ionic'),
    logo('capacitor', 'Capacitor'),
  ],
  [
    logo('docker', 'Docker'),
    logo('githubactions', 'GitHub Actions'),
    logo('concept-cloud-cog', 'Azure & AWS', 'concept'),
  ],
  [logo('concept-book-open', 'Knowledge Center', 'concept')],
  [
    logo('githubactions', 'GitHub Actions'),
    logo('docker', 'Docker'),
    logo('concept-workflow', 'CI/CD', 'concept'),
    logo('concept-bot', 'AI Automation', 'concept'),
  ],
];
const innovation = (
  id: string,
  title: string,
  status: PortfolioProject['status'],
  summary: string,
  technologies: string[],
  sortOrder: number,
): PortfolioProject => ({
  id,
  title,
  category: 'Enterprise Innovation',
  section: 'innovation',
  status,
  summary,
  technologies,
  sortOrder,
  icon: innovationIcons[sortOrder - 1],
  logos: innovationLogos[sortOrder - 1],
});

export const PORTFOLIO_PROJECTS: readonly PortfolioProject[] = [
  {
    id: 'llenroc-tech',
    title: 'Llenroc Tech',
    category: 'Technology Consulting Website',
    section: 'featured',
    status: 'Live',
    summary:
      'The corporate digital platform for Llenroc Tech, presenting software-development services, enterprise capabilities, technical insights, project work, and AI-assisted experiences.',
    technologies: [
      'Angular',
      'TypeScript',
      'Netlify',
      'Azure OpenAI',
      'Netlify Functions',
      'Responsive Design',
    ],
    image: 'assets/img/all-images/portfolio/projects/llenroc-tech-home.png',
    imageAlt: 'Llenroc Tech enterprise consulting website homepage',
    liveUrl: 'https://llenroctech.com/',
    external: true,
    featured: true,
    sortOrder: 1,
  },
  {
    id: 'reddick-foundation',
    title: 'The Reddick Foundation',
    category: 'Nonprofit Website',
    section: 'featured',
    status: 'Live',
    summary:
      'A responsive nonprofit website designed and developed to support the foundation’s mission, community engagement, contact outreach, and future program growth.',
    description:
      'Designed and developed by Llenroc Tech for The Reddick Foundation.',
    technologies: [
      'Angular',
      'TypeScript',
      'Netlify',
      'Netlify Forms',
      'Responsive Design',
    ],
    image: 'assets/img/all-images/portfolio/projects/reddick-foundation.png',
    imageAlt: 'The Reddick Foundation nonprofit website news experience',
    liveUrl: 'https://thereddickfoundation.com/',
    external: true,
    featured: true,
    sortOrder: 2,
  },
  {
    id: 'robot-mower',
    title: 'Robot Mower Platform',
    category: 'Autonomous Product Experience',
    section: 'featured',
    status: 'Live Concept Demo',
    summary:
      'A software concept demonstrating autonomous mower selection, terrain intelligence, product comparison, interactive experiences, and AI-assisted customer guidance.',
    technologies: [
      'Angular',
      'TypeScript',
      'Responsive UI',
      'Azure Static Web Apps',
      'AI-Assisted Experience',
    ],
    image: 'assets/img/all-images/portfolio/projects/robot-mower-platform.png',
    imageAlt: 'Robot Mower Platform concept homepage with autonomous mower',
    liveUrl: 'https://robot.llenroctech.com/',
    external: true,
    disclaimer:
      'Software and product-experience concept created by Llenroc Tech. Llenroc Tech does not currently manufacture or sell physical robotic mowers.',
    featured: true,
    sortOrder: 3,
  },
  {
    id: 'push-up-sit-up-365',
    title: 'Push-Up Sit-Up 365',
    category: 'Fitness Accountability Platform',
    section: 'featured',
    status: 'Live',
    summary:
      'A fitness accountability platform for tracking daily push-ups, sit-ups, challenge progress, workout consistency, and long-term fitness participation.',
    technologies: ['Angular', 'TypeScript', 'Supabase', 'SSR', 'Netlify'],
    image: 'assets/img/all-images/portfolio/projects/push-up-sit-up-365.png',
    imageAlt: 'Push-Up Sit-Up 365 daily fitness accountability dashboard',
    liveUrl: 'https://pu-su-365.com/',
    external: true,
    roadmap: [
      'Ionic and Capacitor mobile application',
      'Strava integration',
      'Expanded progress analytics',
      'Challenge and community capabilities',
    ],
    featured: true,
    sortOrder: 4,
  },
  {
    id: 'enterprise-customer-platform',
    title: 'Enterprise Customer Platform',
    category: 'Enterprise Business Operations Platform',
    section: 'featured',
    status: 'Live',
    summary:
      'A full-stack business operations suite unifying customer management, invoicing, workforce workflows, reporting, administration, and AI-assisted operational insights in one secure workspace.',
    technologies: [
      'Angular',
      'Spring Boot',
      'Java',
      'MySQL',
      'REST APIs',
      'GitHub Actions',
      'Twilio',
      'AI-Assisted Experience',
    ],
    image:
      'assets/img/all-images/portfolio/projects/enterprise-customer-platform.png',
    imageAlt:
      'Llenroc Tech Operations Suite enterprise operations dashboard',
    liveUrl: 'https://customerconnect.llenroctech.com/',
    external: true,
    featured: true,
    sortOrder: 5,
  },
  innovation(
    'enterprise-ai-platform',
    'Enterprise AI Platform',
    'In Development',
    'An enterprise foundation for building AI-assisted business applications, intelligent workflows, reusable integrations, and governed LLM capabilities.',
    ['Python', 'FastAPI', 'LangGraph', 'RAG', 'Vector Databases', 'LLM APIs'],
    1,
  ),
  innovation(
    'ai-engineering-labs',
    'AI Engineering Labs',
    'In Development',
    'Focused engineering laboratories for implementing and validating enterprise AI patterns through real applications.',
    ['Python', 'FastAPI', 'LangGraph', 'CrewAI', 'RAG', 'Observability'],
    2,
  ),
  innovation(
    'fastapi-lab',
    'FastAPI Engineering Lab',
    'Coming Soon',
    'Production-oriented Python API services focused on validation, security, testing, observability, and cloud-ready deployment.',
    ['Python', 'FastAPI', 'Testing', 'Observability'],
    3,
  ),
  innovation(
    'langgraph-lab',
    'LangGraph Workflow Lab',
    'Coming Soon',
    'Stateful, multi-step AI workflows designed for controlled reasoning, tool use, human review, and enterprise automation.',
    ['LangGraph', 'Python', 'LLM APIs'],
    4,
  ),
  innovation(
    'crewai-lab',
    'CrewAI Multi-Agent Lab',
    'Coming Soon',
    'Multi-agent collaboration patterns for research, planning, task execution, and structured business workflows.',
    ['CrewAI', 'Python', 'Multi-Agent Systems'],
    5,
  ),
  innovation(
    'rag-platform',
    'RAG Knowledge Platform',
    'Coming Soon',
    'Enterprise knowledge retrieval combining document ingestion, embeddings, semantic search, grounded generation, and access-aware responses.',
    ['RAG', 'Embeddings', 'Semantic Search'],
    6,
  ),
  innovation(
    'vector-db-lab',
    'Vector Database Lab',
    'Research',
    'Practical evaluation of vector storage, retrieval quality, filtering, indexing, and integration patterns for AI applications.',
    ['Vector Databases', 'RAG', 'Python'],
    7,
  ),
  innovation(
    'llm-integrations',
    'LLM Provider Integrations',
    'Research',
    'Reusable integration patterns for modern LLM providers while maintaining portability, security, and operational control.',
    ['OpenAI', 'Anthropic', 'Gemini', 'Azure OpenAI'],
    8,
  ),
  innovation(
    'ai-observability',
    'AI Observability and Evaluation',
    'Coming Soon',
    'Tracing, evaluation, monitoring, prompt analysis, quality measurement, and operational visibility for enterprise AI systems.',
    ['Observability', 'Evaluation', 'LLM APIs'],
    9,
  ),
  innovation(
    'engineering-agents',
    'Engineering Agents',
    'In Development',
    'Specialized internal agents supporting architecture review, code quality, security, testing, documentation, releases, and deployment readiness.',
    ['AI Agents', 'Testing', 'Automation'],
    10,
  ),
  innovation(
    'support-agent',
    'Customer Support AI Agent',
    'Coming Soon',
    'An AI-assisted customer support experience designed for knowledge retrieval, workflow guidance, escalation, and controlled business integration.',
    ['RAG', 'AI Agents', 'Workflow Automation'],
    11,
  ),
  innovation(
    'analytics-platform',
    'Enterprise Analytics Platform',
    'Coming Soon',
    'Business dashboards, operational reporting, real-time insights, and future AI-assisted analytics experiences.',
    ['Analytics', 'Dashboards', 'Data Platforms'],
    12,
  ),
  innovation(
    'llenroc-mobile',
    'Llenroc Tech Mobile',
    'Coming Soon',
    'Cross-platform mobile applications built with Angular, Ionic, and Capacitor for iOS and Android experiences.',
    ['Angular', 'Ionic', 'Capacitor'],
    13,
  ),
  innovation(
    'cloud-platform',
    'Cloud Deployment Platform',
    'Research',
    'Repeatable deployment patterns using containers, CI/CD, infrastructure automation, monitoring, and modern cloud platforms.',
    ['Docker', 'GitHub Actions', 'Azure', 'AWS'],
    14,
  ),
  innovation(
    'knowledge-center',
    'Knowledge Center',
    'In Development',
    'Technical articles, engineering guidance, architecture documentation, and practical resources from Llenroc Tech.',
    ['Angular', 'Technical Writing', 'Architecture'],
    15,
  ),
  innovation(
    'engineering-automation',
    'Engineering Automation',
    'Research',
    'Automated workflows for code review, testing, release preparation, documentation, repository governance, and delivery operations.',
    ['Automation', 'GitHub Actions', 'AI Agents'],
    16,
  ),
];

export const TRUSTED_TECHNOLOGIES = [
  'Angular',
  'TypeScript',
  'Java',
  'Spring Boot',
  'Python',
  'FastAPI',
  'Ionic',
  'Capacitor',
  'MySQL',
  'PostgreSQL',
  'Supabase',
  'Docker',
  'GitHub Actions',
  'Netlify',
  'Azure',
  'AWS',
  'OpenAI',
  'Azure OpenAI',
  'Anthropic',
  'Gemini',
  'LangGraph',
  'CrewAI',
  'RAG',
  'Vector Databases',
] as const;
