import { PortfolioProject } from './portfolio.models';

const innovation = (id: string, title: string, status: PortfolioProject['status'], summary: string, technologies: string[], sortOrder: number): PortfolioProject => ({ id, title, category: 'Enterprise Innovation', section: 'innovation', status, summary, technologies, sortOrder });

export const PORTFOLIO_PROJECTS: readonly PortfolioProject[] = [
  { id:'llenroc-tech', title:'Llenroc Tech', category:'Technology Consulting Website', section:'featured', status:'Live', summary:'The corporate digital platform for Llenroc Tech, presenting software-development services, enterprise capabilities, technical insights, project work, and AI-assisted experiences.', technologies:['Angular','TypeScript','Netlify','Azure OpenAI','Netlify Functions','Responsive Design'], internalRoute:'/home', featured:true, sortOrder:1 },
  { id:'reddick-foundation', title:'The Reddick Foundation', category:'Nonprofit Website', section:'featured', status:'Live', summary:'A responsive nonprofit website designed and developed to support the foundation’s mission, community engagement, contact outreach, and future program growth.', description:'Designed and developed by Llenroc Tech for The Reddick Foundation.', technologies:['Angular','TypeScript','Netlify','Netlify Forms','Responsive Design'], liveUrl:'https://thereddickfoundation.com/', external:true, featured:true, sortOrder:2 },
  { id:'robot-mower', title:'Robot Mower Platform', category:'Autonomous Product Experience', section:'featured', status:'Live Concept Demo', summary:'A software concept demonstrating autonomous mower selection, terrain intelligence, product comparison, interactive experiences, and AI-assisted customer guidance.', technologies:['Angular','TypeScript','Responsive UI','Azure Static Web Apps','AI-Assisted Experience'], liveUrl:'https://robot.llenroctech.com/', external:true, disclaimer:'Software and product-experience concept created by Llenroc Tech. Llenroc Tech does not currently manufacture or sell physical robotic mowers.', featured:true, sortOrder:3 },
  { id:'push-up-sit-up-365', title:'Push-Up Sit-Up 365', category:'Fitness Accountability Platform', section:'featured', status:'Live', summary:'A fitness accountability platform for tracking daily push-ups, sit-ups, challenge progress, workout consistency, and long-term fitness participation.', technologies:['Angular','TypeScript','Supabase','SSR','Netlify'], liveUrl:'https://pu-su-365.com/', external:true, roadmap:['Ionic and Capacitor mobile application','Strava integration','Expanded progress analytics','Challenge and community capabilities'], featured:true, sortOrder:4 },
  { id:'enterprise-customer-platform', title:'Enterprise Customer Platform', category:'Enterprise Software', section:'featured', status:'Coming Soon', summary:'A modern full-stack customer platform demonstrating secure registration, authentication, account verification, MFA, REST APIs, database integration, automated testing, CI/CD, and enterprise application architecture.', technologies:['Angular','Spring Boot','Java','MySQL','REST APIs','GitHub Actions','Twilio'], featured:true, sortOrder:5 },
  { id:'corporate-landing-concept', title:'Corporate Landing Experience', category:'Corporate Website', section:'templates', status:'Design Concept', summary:'A polished corporate landing-page direction recovered from the earlier Angular site preview assets.', image:'assets/img/all-images/hero/preview-img1.png', imageAlt:'Corporate landing page design concept', technologies:['Angular','Responsive Design'], sortOrder:1 },
  { id:'portfolio-concept', title:'Professional Portfolio Concept', category:'Portfolio Website', section:'templates', status:'Design Concept', summary:'A visual portfolio direction preserved from the website’s original template assets.', image:'assets/img/all-images/portfolio/portfolio-img2.png', imageAlt:'Professional portfolio website design concept', technologies:['Angular','SCSS','Responsive Design'], sortOrder:2 },
  innovation('enterprise-ai-platform','Enterprise AI Platform','In Development','An enterprise foundation for building AI-assisted business applications, intelligent workflows, reusable integrations, and governed LLM capabilities.',['Python','FastAPI','LangGraph','RAG','Vector Databases','LLM APIs'],1),
  innovation('ai-engineering-labs','AI Engineering Labs','In Development','Focused engineering laboratories for implementing and validating enterprise AI patterns through real applications.',['Python','FastAPI','LangGraph','CrewAI','RAG','Observability'],2),
  innovation('fastapi-lab','FastAPI Engineering Lab','Coming Soon','Production-oriented Python API services focused on validation, security, testing, observability, and cloud-ready deployment.',['Python','FastAPI','Testing','Observability'],3),
  innovation('langgraph-lab','LangGraph Workflow Lab','Coming Soon','Stateful, multi-step AI workflows designed for controlled reasoning, tool use, human review, and enterprise automation.',['LangGraph','Python','LLM APIs'],4),
  innovation('crewai-lab','CrewAI Multi-Agent Lab','Coming Soon','Multi-agent collaboration patterns for research, planning, task execution, and structured business workflows.',['CrewAI','Python','Multi-Agent Systems'],5),
  innovation('rag-platform','RAG Knowledge Platform','Coming Soon','Enterprise knowledge retrieval combining document ingestion, embeddings, semantic search, grounded generation, and access-aware responses.',['RAG','Embeddings','Semantic Search'],6),
  innovation('vector-db-lab','Vector Database Lab','Research','Practical evaluation of vector storage, retrieval quality, filtering, indexing, and integration patterns for AI applications.',['Vector Databases','RAG','Python'],7),
  innovation('llm-integrations','LLM Provider Integrations','Research','Reusable integration patterns for modern LLM providers while maintaining portability, security, and operational control.',['OpenAI','Anthropic','Gemini','Azure OpenAI'],8),
  innovation('ai-observability','AI Observability and Evaluation','Coming Soon','Tracing, evaluation, monitoring, prompt analysis, quality measurement, and operational visibility for enterprise AI systems.',['Observability','Evaluation','LLM APIs'],9),
  innovation('engineering-agents','Engineering Agents','In Development','Specialized internal agents supporting architecture review, code quality, security, testing, documentation, releases, and deployment readiness.',['AI Agents','Testing','Automation'],10),
  innovation('support-agent','Customer Support AI Agent','Coming Soon','An AI-assisted customer support experience designed for knowledge retrieval, workflow guidance, escalation, and controlled business integration.',['RAG','AI Agents','Workflow Automation'],11),
  innovation('analytics-platform','Enterprise Analytics Platform','Coming Soon','Business dashboards, operational reporting, real-time insights, and future AI-assisted analytics experiences.',['Analytics','Dashboards','Data Platforms'],12),
  innovation('llenroc-mobile','Llenroc Tech Mobile','Coming Soon','Cross-platform mobile applications built with Angular, Ionic, and Capacitor for iOS and Android experiences.',['Angular','Ionic','Capacitor'],13),
  innovation('cloud-platform','Cloud Deployment Platform','Research','Repeatable deployment patterns using containers, CI/CD, infrastructure automation, monitoring, and modern cloud platforms.',['Docker','GitHub Actions','Azure','AWS'],14),
  innovation('knowledge-center','Knowledge Center','In Development','Technical articles, engineering guidance, architecture documentation, and practical resources from Llenroc Tech.',['Angular','Technical Writing','Architecture'],15),
  innovation('engineering-automation','Engineering Automation','Research','Automated workflows for code review, testing, release preparation, documentation, repository governance, and delivery operations.',['Automation','GitHub Actions','AI Agents'],16),
];

export const TRUSTED_TECHNOLOGIES = ['Angular','TypeScript','Java','Spring Boot','Python','FastAPI','Ionic','Capacitor','MySQL','PostgreSQL','Supabase','Docker','GitHub Actions','Netlify','Azure','AWS','OpenAI','Azure OpenAI','Anthropic','Gemini','LangGraph','CrewAI','RAG','Vector Databases'] as const;
